all: safeadd safesubtract safemultiply safedivide

safeint.o: safeint.c safeint.h
	gcc -c safeint.c -o safeint.o

safeadd: safeadd.c safeint.o
	gcc safeadd.c safeint.o -o safeadd

safesubtract: safesubtract.c safeint.o
	gcc safesubtract.c safeint.o -o safesubtract

safemultiply: safemultiply.c safeint.o
	gcc safemultiply.c safeint.o -o safemultiply

safedivide: safedivide.c safeint.o
	gcc safedivide.c safeint.o -o safedivide

clean:
	rm -f *.o safeadd safesubtract safemultiply safedivide
